[package]
name = "go_play_adblock_jni"
version = "0.1.0"
edition = "2021"

[lib]
name = "go_play_adblock_jni"
crate-type = ["cdylib"]

[dependencies]
adblock = { git = "https://github.com/brave/adblock-rust.git", rev = "0de87f2fd0dc1c5830e46352f1936576b02f0c06", default-features = false, features = ["embedded-domain-resolver", "full-regex-handling"] }
base64 = "0.22"
jni = "0.21.1"
serde_json = "1.0"
