[package]
name = "go_play_adblock_jni"
version = "0.1.0"
edition = "2021"

[lib]
name = "go_play_adblock_jni"
crate-type = ["cdylib"]

[dependencies]
adblock = { version = "0.12.1", default-features = false, features = ["embedded-domain-resolver", "full-regex-handling"] }
base64 = "0.22"
jni = "0.21.1"
serde_json = "1.0"
